resolver: lts-5.16
packages:
- '.'
- location:
    git: https://github.com/oisdk/Square.git
    commit: b8d6b9feca60c105f60c585bb3cdc89752a22381
- location:
    git: https://github.com/oisdk/Expr.git
    commit: 166e416ac892edf122daad5ab7ec0dfc96f60e68
- location:
    git: https://github.com/ekmett/recursion-schemes.git
    commit: cf42f2ace35ca09a8ab489538e9493f8333bc0ec
- location:
    git: https://github.com/oisdk/recursion-schemes-extras.git
    commit: cf40fb2cf971326a5929cddae223770bd256df86
extra-deps:
- taggy-0.2.0
- taggy-lens-0.1.2
flags: {}
extra-package-dbs: []
